In [2]:
import sys
import os
import torch
import torch.utils.data as data
import torch.nn as nn

sys.path.append(os.path.abspath('../'))

from neuro_fuzzy_toolbox import ANFIS
#from neuro_fuzzy_toolbox import 

In [2]:
x = torch.rand(10, 2)
y = torch.rand(10, 2)

In [3]:
model = ANFIS(input_size=2, fuzzy_rules=3, outputs=2, rule_reduced=True)
model.init_premises(x_train=x)

In [4]:
model._fuzzification_layer(x)

tensor([[[3.8210e-06, 1.0000e+00, 6.9478e-05],
         [8.7600e-01, 1.4906e-01, 1.2724e-08]],

        [[8.8387e-05, 1.0000e+00, 3.1343e-06],
         [1.0000e+00, 1.5259e-05, 2.3283e-10]],

        [[9.1105e-06, 1.0000e+00, 2.5998e-05],
         [3.3059e-01, 6.7657e-01, 2.9599e-08]],

        [[3.4173e-07, 9.9995e-01, 2.2400e-03],
         [2.3283e-10, 1.5259e-05, 1.0000e+00]],

        [[1.0000e+00, 1.5259e-05, 2.3283e-10],
         [4.9335e-10, 7.1084e-05, 1.0000e+00]],

        [[1.3371e-09, 6.2328e-04, 1.0000e+00],
         [3.4949e-08, 7.7867e-01, 2.3754e-01]],

        [[1.0604e-08, 9.5698e-02, 9.3173e-01],
         [1.8322e-01, 8.3874e-01, 3.9505e-08]],

        [[1.0000e+00, 2.9678e-05, 3.2359e-10],
         [1.0000e+00, 1.0993e-04, 6.0623e-10]],

        [[9.9999e-01, 1.2417e-03, 1.8075e-09],
         [2.6563e-10, 1.9882e-05, 1.0000e+00]],

        [[2.3283e-10, 1.5259e-05, 1.0000e+00],
         [5.6011e-08, 9.4269e-01, 8.4522e-02]]], grad_fn=<MulBackward0>)

In [5]:
model._consequent_layer(x, model._normalization_layer(model._firing_levels_layer(model._fuzzification_layer(x))))

tensor([[[-1.7229e-05, -3.7194e-01, -4.9185e-13],
         [-6.3181e-01, -5.5675e-02, -1.5011e-12],
         [-3.2807e-06, -3.4127e-01, -1.0159e-13],
         [-2.3591e-14, -1.2766e-03,  2.1062e-01],
         [-5.4286e-02,  1.2041e-01, -2.7153e-02],
         [-1.8146e-16, -8.9452e-04,  2.9883e-01],
         [-2.2734e-08, -5.1001e-01,  4.1196e-08],
         [-4.0530e-01, -2.8678e-10, -9.2499e-20],
         [-2.8003e-03,  1.2550e-01, -8.2460e-03],
         [-1.5535e-16, -8.6977e-05,  3.5970e-01]],

        [[-6.2811e-06, -2.0135e-01,  9.4190e-13],
         [-3.7768e-01, -3.2840e-02,  1.2040e-12],
         [-1.2225e-06, -2.3536e-01,  1.6539e-13],
         [ 5.6920e-15, -2.2461e-03,  5.4443e-02],
         [-5.3248e-02, -5.0212e-01, -1.1671e-02],
         [ 3.2058e-17, -9.6268e-05,  1.6113e-01],
         [-3.0302e-09, -1.7027e-02,  9.5727e-08],
         [-6.3849e-01, -1.9177e-09,  1.1471e-20],
         [-1.1229e-03, -6.9175e-01, -4.5811e-03],
         [ 3.1932e-17,  7.3043e-06,  1.8982e-01]

In [6]:
model._output_layer(model._consequent_layer(x, model._normalization_layer(model._firing_levels_layer(model._fuzzification_layer(x)))))

tensor([[-0.3720, -0.2014],
        [-0.6875, -0.4105],
        [-0.3413, -0.2354],
        [ 0.2093,  0.0522],
        [ 0.0390, -0.5670],
        [ 0.2979,  0.1610],
        [-0.5100, -0.0170],
        [-0.4053, -0.6385],
        [ 0.1145, -0.6975],
        [ 0.3596,  0.1898]], grad_fn=<SqueezeBackward1>)

In [7]:
model._output_layer(model._consequent_layer(x, model._normalization_layer(model._firing_levels_layer(model._fuzzification_layer(x))))).squeeze(1)

tensor([[-0.3720, -0.2014],
        [-0.6875, -0.4105],
        [-0.3413, -0.2354],
        [ 0.2093,  0.0522],
        [ 0.0390, -0.5670],
        [ 0.2979,  0.1610],
        [-0.5100, -0.0170],
        [-0.4053, -0.6385],
        [ 0.1145, -0.6975],
        [ 0.3596,  0.1898]], grad_fn=<SqueezeBackward1>)

In [8]:
x = torch.rand(10, 2)
y = torch.rand(10, 3)

In [9]:
model = ANFIS(input_size=2, fuzzy_rules=3, outputs=3, rule_reduced=True)
model.init_premises(x_train=x)

In [10]:
model._fuzzification_layer(x)

tensor([[[1.0000e+00, 1.5259e-05, 2.3283e-10],
         [1.0448e-03, 1.0000e+00, 5.4035e-07]],

        [[6.2918e-09, 2.5666e-02, 9.9111e-01],
         [1.5354e-08, 2.2943e-01, 7.8765e-01]],

        [[1.2885e-05, 1.0000e+00, 1.8103e-05],
         [1.0815e-07, 9.9420e-01, 2.0103e-02]],

        [[3.7557e-08, 8.1559e-01, 2.0420e-01],
         [2.0707e-08, 4.1521e-01, 5.8661e-01]],

        [[3.0740e-03, 9.9989e-01, 2.8533e-07],
         [4.8384e-03, 9.9968e-01, 2.2237e-07]],

        [[1.0000e+00, 4.6003e-04, 1.1681e-09],
         [2.3283e-10, 1.5259e-05, 1.0000e+00]],

        [[2.0024e-04, 1.0000e+00, 1.6620e-06],
         [9.9094e-01, 2.5956e-02, 6.3199e-09]],

        [[4.6991e-02, 9.7611e-01, 7.2906e-08],
         [6.5569e-06, 1.0000e+00, 3.7219e-05]],

        [[9.7993e-01, 4.2066e-02, 7.6476e-09],
         [9.9998e-01, 1.6252e-03, 2.0294e-09]],

        [[2.3283e-10, 1.5259e-05, 1.0000e+00],
         [1.0000e+00, 1.5259e-05, 2.3283e-10]]], grad_fn=<MulBackward0>)

In [11]:
model._consequent_layer(x, model._normalization_layer(model._firing_levels_layer(model._fuzzification_layer(x))))

tensor([[[-4.3907e-01, -8.5435e-03,  7.1832e-14],
         [-1.6105e-18, -7.0102e-03,  9.1884e-01],
         [-1.8662e-13, -8.4072e-01,  2.9521e-07],
         [-6.5646e-17, -6.7655e-01,  2.3332e-01],
         [-6.1080e-06, -6.2284e-01,  4.6884e-14],
         [ 1.0576e-03, -8.1083e-01,  9.2257e-02],
         [-3.9610e-03, -5.3178e-01,  3.0420e-13],
         [-8.9976e-08, -7.2073e-01,  2.0129e-12],
         [-6.0693e-01, -3.2662e-05,  1.0593e-17],
         [-1.8829e-01, -1.6850e-01,  3.2198e-01]],

        [[ 5.0040e-01,  1.4540e-02,  8.1607e-14],
         [ 7.6493e-18,  4.8965e-03,  6.4244e-01],
         [ 3.1739e-13,  7.9971e-01,  2.4500e-07],
         [ 1.8186e-16,  5.1455e-01,  1.7106e-01],
         [ 4.8789e-06,  8.1503e-01,  4.0996e-14],
         [ 1.1312e-02,  8.9523e-01,  1.0396e-01],
         [ 2.3289e-03,  7.4413e-01,  2.4896e-13],
         [ 1.0812e-07,  8.7809e-01,  1.8700e-12],
         [ 4.2867e-01,  5.9952e-05,  1.0088e-17],
         [ 9.9063e-03,  1.3784e-01,  1.7931e-01]

In [12]:
model._output_layer(model._consequent_layer(x, model._normalization_layer(model._firing_levels_layer(model._fuzzification_layer(x)))))

tensor([[-0.4476,  0.5149, -0.1259],
        [ 0.9118,  0.6473,  0.0467],
        [-0.8407,  0.7997,  0.2133],
        [-0.4432,  0.6856,  0.3052],
        [-0.6228,  0.8150,  0.0612],
        [-0.7175,  1.0105,  0.0973],
        [-0.5357,  0.7465,  0.0779],
        [-0.7207,  0.8781,  0.0508],
        [-0.6070,  0.4287, -0.2429],
        [-0.0348,  0.3271, -0.2196]], grad_fn=<SqueezeBackward1>)

In [13]:
model._output_layer(model._consequent_layer(x, model._normalization_layer(model._firing_levels_layer(model._fuzzification_layer(x))))).squeeze(1)

tensor([[-0.4476,  0.5149, -0.1259],
        [ 0.9118,  0.6473,  0.0467],
        [-0.8407,  0.7997,  0.2133],
        [-0.4432,  0.6856,  0.3052],
        [-0.6228,  0.8150,  0.0612],
        [-0.7175,  1.0105,  0.0973],
        [-0.5357,  0.7465,  0.0779],
        [-0.7207,  0.8781,  0.0508],
        [-0.6070,  0.4287, -0.2429],
        [-0.0348,  0.3271, -0.2196]], grad_fn=<SqueezeBackward1>)

# Consequents

In [3]:
x = torch.rand(10, 2)
x

tensor([[0.0745, 0.5577],
        [0.7567, 0.1957],
        [0.7193, 0.6300],
        [0.2667, 0.5187],
        [0.3195, 0.4542],
        [0.6371, 0.0578],
        [0.3001, 0.9271],
        [0.1746, 0.4842],
        [0.8812, 0.4591],
        [0.8327, 0.8224]])

In [4]:
y = torch.rand(10)
y

tensor([0.4628, 0.0548, 0.8754, 0.1947, 0.5860, 0.4808, 0.7440, 0.9061, 0.2606,
        0.9658])

In [5]:
model = ANFIS(
    input_size = 2,
    fuzzy_rules = 3,
    outputs = 1
)

In [6]:
model.init_premises(x)
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1  0.000751 -0.622371  0.461999
rule 2 -0.913493 -0.302936  0.321753
rule 3 -0.760362 -0.170394  0.103371
rule 4  0.926840 -0.523038  0.485536
rule 5 -0.922145 -0.843955 -0.513963
rule 6  0.090786  0.357548 -0.778427
rule 7  0.261330  0.169342 -0.816505
rule 8  0.357780  0.655499  0.287269
rule 9 -0.831793  0.315424 -0.268871




In [8]:
current_consequents = model.get_consequents()
new_consequents = torch.zeros_like(current_consequents)
_, w_norm, _ = model.intermediate_values(x)

In [12]:
current_consequents.shape

torch.Size([1, 9, 3])

In [9]:
w_norm.shape

torch.Size([10, 9])

In [10]:
xe = torch.cat([x, torch.ones(x.shape[0], 1)], dim=1)
xe

tensor([[0.0745, 0.5577, 1.0000],
        [0.7567, 0.1957, 1.0000],
        [0.7193, 0.6300, 1.0000],
        [0.2667, 0.5187, 1.0000],
        [0.3195, 0.4542, 1.0000],
        [0.6371, 0.0578, 1.0000],
        [0.3001, 0.9271, 1.0000],
        [0.1746, 0.4842, 1.0000],
        [0.8812, 0.4591, 1.0000],
        [0.8327, 0.8224, 1.0000]])

In [13]:
w_norm

tensor([[1.6288e-06, 9.9978e-01, 2.0567e-04, 2.4853e-11, 1.5255e-05, 3.1382e-09,
         3.7923e-16, 2.3278e-10, 4.7885e-14],
        [3.3569e-09, 2.2772e-11, 1.2386e-17, 5.4837e-03, 3.7200e-05, 2.0234e-11,
         9.8778e-01, 6.7008e-03, 3.6448e-09],
        [1.5260e-15, 8.1307e-09, 5.4270e-11, 9.6620e-09, 5.1482e-02, 3.4363e-04,
         1.7677e-07, 9.4189e-01, 6.2868e-03],
        [4.0488e-06, 6.7756e-01, 2.7985e-05, 1.9265e-06, 3.2239e-01, 1.3316e-05,
         1.0755e-13, 1.7998e-08, 7.4337e-13],
        [2.7683e-06, 4.1546e-02, 1.6440e-07, 6.3859e-05, 9.5838e-01, 3.7923e-06,
         4.9763e-12, 7.4684e-08, 2.9552e-13],
        [7.2576e-08, 1.1074e-12, 1.6898e-17, 9.5582e-01, 1.4584e-05, 2.2254e-10,
         4.4166e-02, 6.7391e-07, 1.0283e-11],
        [3.2392e-11, 2.1228e-06, 1.3912e-01, 2.0043e-10, 1.3135e-05, 8.6086e-01,
         1.0056e-17, 6.5900e-13, 4.3189e-08],
        [2.0729e-05, 9.9851e-01, 1.1264e-05, 3.0327e-08, 1.4608e-03, 1.6479e-08,
         4.0211e-14, 1.9370e-0

In [14]:
fs = w_norm.unsqueeze(2).repeat(1, 1, xe.shape[1]).view(w_norm.shape[0], -1)
fs.shape

torch.Size([10, 27])

In [15]:
X = xe.repeat(1, model.rules)
X

tensor([[0.0745, 0.5577, 1.0000, 0.0745, 0.5577, 1.0000, 0.0745, 0.5577, 1.0000,
         0.0745, 0.5577, 1.0000, 0.0745, 0.5577, 1.0000, 0.0745, 0.5577, 1.0000,
         0.0745, 0.5577, 1.0000, 0.0745, 0.5577, 1.0000, 0.0745, 0.5577, 1.0000],
        [0.7567, 0.1957, 1.0000, 0.7567, 0.1957, 1.0000, 0.7567, 0.1957, 1.0000,
         0.7567, 0.1957, 1.0000, 0.7567, 0.1957, 1.0000, 0.7567, 0.1957, 1.0000,
         0.7567, 0.1957, 1.0000, 0.7567, 0.1957, 1.0000, 0.7567, 0.1957, 1.0000],
        [0.7193, 0.6300, 1.0000, 0.7193, 0.6300, 1.0000, 0.7193, 0.6300, 1.0000,
         0.7193, 0.6300, 1.0000, 0.7193, 0.6300, 1.0000, 0.7193, 0.6300, 1.0000,
         0.7193, 0.6300, 1.0000, 0.7193, 0.6300, 1.0000, 0.7193, 0.6300, 1.0000],
        [0.2667, 0.5187, 1.0000, 0.2667, 0.5187, 1.0000, 0.2667, 0.5187, 1.0000,
         0.2667, 0.5187, 1.0000, 0.2667, 0.5187, 1.0000, 0.2667, 0.5187, 1.0000,
         0.2667, 0.5187, 1.0000, 0.2667, 0.5187, 1.0000, 0.2667, 0.5187, 1.0000],
        [0.3195, 0.4542,

In [16]:
fs

tensor([[1.6288e-06, 1.6288e-06, 1.6288e-06, 9.9978e-01, 9.9978e-01, 9.9978e-01,
         2.0567e-04, 2.0567e-04, 2.0567e-04, 2.4853e-11, 2.4853e-11, 2.4853e-11,
         1.5255e-05, 1.5255e-05, 1.5255e-05, 3.1382e-09, 3.1382e-09, 3.1382e-09,
         3.7923e-16, 3.7923e-16, 3.7923e-16, 2.3278e-10, 2.3278e-10, 2.3278e-10,
         4.7885e-14, 4.7885e-14, 4.7885e-14],
        [3.3569e-09, 3.3569e-09, 3.3569e-09, 2.2772e-11, 2.2772e-11, 2.2772e-11,
         1.2386e-17, 1.2386e-17, 1.2386e-17, 5.4837e-03, 5.4837e-03, 5.4837e-03,
         3.7200e-05, 3.7200e-05, 3.7200e-05, 2.0234e-11, 2.0234e-11, 2.0234e-11,
         9.8778e-01, 9.8778e-01, 9.8778e-01, 6.7008e-03, 6.7008e-03, 6.7008e-03,
         3.6448e-09, 3.6448e-09, 3.6448e-09],
        [1.5260e-15, 1.5260e-15, 1.5260e-15, 8.1307e-09, 8.1307e-09, 8.1307e-09,
         5.4270e-11, 5.4270e-11, 5.4270e-11, 9.6620e-09, 9.6620e-09, 9.6620e-09,
         5.1482e-02, 5.1482e-02, 5.1482e-02, 3.4363e-04, 3.4363e-04, 3.4363e-04,
         1.7677e-

In [17]:
A = fs * X
A.shape

torch.Size([10, 27])

In [18]:
y.shape

torch.Size([10])

In [19]:
C, res, rank, sing_val = torch.linalg.lstsq(A, y)

In [20]:
C

tensor([2.2174e-06, 5.8527e-06, 1.2060e-05, 1.2448e-01, 3.2540e-01, 6.6198e-01,
        2.5706e-06, 7.4452e-06, 1.4322e-05, 4.1438e-03, 3.8015e-04, 6.5078e-03,
        5.3599e-02, 8.3526e-02, 1.7657e-01, 1.0920e-06, 2.4651e-06, 3.8458e-06,
        4.7042e-04, 8.9546e-05, 6.6909e-04, 1.9021e-06, 4.9717e-07, 2.5223e-06,
        1.9911e-12, 1.1693e-12, 2.8227e-12])

In [29]:
C.reshape(model.rules, xe.shape[1])

tensor([[-2.9214e-02,  2.0747e-01,  7.9621e-01],
        [ 2.2515e-01,  3.4417e-01,  6.5451e-01],
        [ 5.3066e-05,  5.9286e-05,  8.9299e-05],
        [-1.9079e-02, -9.5210e-06, -5.0267e-02],
        [-2.8430e+00,  2.8209e+00,  3.9578e-01],
        [ 2.9142e+01,  2.8012e+01,  3.3623e+01],
        [ 5.1218e-01,  4.0773e-01,  5.9661e-01],
        [-1.0351e+00,  3.6320e+00, -1.2824e+00],
        [ 2.3173e+02, -2.9249e+02,  4.3721e+01]])

In [30]:
C.t().reshape(model.rules, xe.shape[1])

tensor([[-2.9214e-02,  2.0747e-01,  7.9621e-01],
        [ 2.2515e-01,  3.4417e-01,  6.5451e-01],
        [ 5.3066e-05,  5.9286e-05,  8.9299e-05],
        [-1.9079e-02, -9.5210e-06, -5.0267e-02],
        [-2.8430e+00,  2.8209e+00,  3.9578e-01],
        [ 2.9142e+01,  2.8012e+01,  3.3623e+01],
        [ 5.1218e-01,  4.0773e-01,  5.9661e-01],
        [-1.0351e+00,  3.6320e+00, -1.2824e+00],
        [ 2.3173e+02, -2.9249e+02,  4.3721e+01]])

In [31]:
C.view(model.rules, xe.shape[1])

tensor([[-2.9214e-02,  2.0747e-01,  7.9621e-01],
        [ 2.2515e-01,  3.4417e-01,  6.5451e-01],
        [ 5.3066e-05,  5.9286e-05,  8.9299e-05],
        [-1.9079e-02, -9.5210e-06, -5.0267e-02],
        [-2.8430e+00,  2.8209e+00,  3.9578e-01],
        [ 2.9142e+01,  2.8012e+01,  3.3623e+01],
        [ 5.1218e-01,  4.0773e-01,  5.9661e-01],
        [-1.0351e+00,  3.6320e+00, -1.2824e+00],
        [ 2.3173e+02, -2.9249e+02,  4.3721e+01]])

In [32]:
x = torch.rand(10, 2)
x

tensor([[0.9764, 0.1513],
        [0.2865, 0.8901],
        [0.2376, 0.1015],
        [0.2705, 0.6237],
        [0.6154, 0.3167],
        [0.0261, 0.2890],
        [0.1766, 0.2615],
        [0.8788, 0.2478],
        [0.4499, 0.5164],
        [0.1011, 0.6679]])

In [33]:
y = torch.rand(10, 2)
y

tensor([[0.9569, 0.7563],
        [0.1063, 0.6841],
        [0.6177, 0.3237],
        [0.0136, 0.7282],
        [0.3715, 0.0496],
        [0.3014, 0.1495],
        [0.7215, 0.9510],
        [0.8720, 0.1037],
        [0.8848, 0.5490],
        [0.3154, 0.4804]])

In [34]:
model = ANFIS(
    input_size = 2,
    fuzzy_rules = 3,
    outputs = 2
)

In [35]:
model.init_premises(x)
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.348215  0.576100 -0.283503
rule 2  0.428027 -0.341832 -0.976921
rule 3  0.733686  0.881873  0.352430
rule 4  0.513434  0.916491  0.209669
rule 5 -0.535595  0.274208 -0.481447
rule 6  0.603007  0.464800  0.172153
rule 7  0.437946  0.958330 -0.875871
rule 8 -0.070247  0.482663 -0.094707
rule 9  0.576644  0.515615  0.071861


- Output 2:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.858555 -0.768257 -0.734525
rule 2 -0.148338 -0.183097  0.322909
rule 3 -0.499968 -0.792542 -0.830621
rule 4  0.035826  0.072405 -0.092548
rule 5  0.204563 -0.620601  0.389144
rule 6  0.577244  0.578324 -0.336328
rule 7  0.108856  0.850732  0.477353
rule 8  0.002853  0.745258  0.585570
rule 9 -0.170875 -0.131813 -0.607211




In [36]:
current_consequents = model.get_consequents()
new_consequents = torch.zeros_like(current_consequents)
_, w_norm = model.intermediate_values(x)
w_norm.shape

torch.Size([10, 9])

In [37]:
xe = torch.cat([x, torch.ones(x.shape[0], 1)], dim=1)
xe

tensor([[0.9764, 0.1513, 1.0000],
        [0.2865, 0.8901, 1.0000],
        [0.2376, 0.1015, 1.0000],
        [0.2705, 0.6237, 1.0000],
        [0.6154, 0.3167, 1.0000],
        [0.0261, 0.2890, 1.0000],
        [0.1766, 0.2615, 1.0000],
        [0.8788, 0.2478, 1.0000],
        [0.4499, 0.5164, 1.0000],
        [0.1011, 0.6679, 1.0000]])

In [38]:
fs = w_norm.unsqueeze(2).repeat(1, 1, xe.shape[1]).view(w_norm.shape[0], -1)
fs.shape

torch.Size([10, 27])

In [39]:
X = xe.repeat(1, model.rules)
X.shape

torch.Size([10, 27])

In [40]:
A = fs * X
A.shape

torch.Size([10, 27])

In [41]:
y.shape

torch.Size([10, 2])

In [42]:
C, res, rank, sing_val = torch.linalg.lstsq(A, y)

In [43]:
C

tensor([[ 1.2883e+00,  3.5645e+00],
        [-1.5760e+00,  3.3643e+00],
        [ 1.0233e+00, -4.4990e-01],
        [-3.0250e+00,  2.9834e+00],
        [ 1.0822e+00,  2.9842e+00],
        [-5.8478e-01, -1.8043e+00],
        [ 2.2267e-01,  5.2966e-02],
        [ 1.6903e+00,  1.9467e-01],
        [ 2.5383e+00,  2.7531e-01],
        [-1.8801e+00,  4.4492e-01],
        [-1.0173e+00,  4.1067e-01],
        [-1.8520e+00, -2.0944e+00],
        [ 2.3343e+00, -5.8094e-01],
        [ 5.4164e-02, -8.2943e-02],
        [-1.9298e-01,  8.5317e-01],
        [-1.2586e-01,  1.1453e-01],
        [-3.4317e-01,  3.2998e-01],
        [-4.5241e-01,  4.0718e-01],
        [ 5.4491e-01,  2.5169e+00],
        [-5.4052e-02, -3.7530e+00],
        [ 4.3319e-01, -1.1332e+00],
        [-3.8786e-02, -8.0073e-01],
        [-1.3723e-02, -2.2445e-01],
        [-4.9978e-02, -9.0770e-01],
        [-9.6825e-09, -1.7629e-07],
        [-1.3796e-08, -3.9755e-08],
        [-2.1168e-08, -1.9151e-07]])

In [44]:
C.shape

torch.Size([27, 2])

In [45]:
C.t().reshape(2, model.rules, xe.shape[1])

tensor([[[ 1.2883e+00, -1.5760e+00,  1.0233e+00],
         [-3.0250e+00,  1.0822e+00, -5.8478e-01],
         [ 2.2267e-01,  1.6903e+00,  2.5383e+00],
         [-1.8801e+00, -1.0173e+00, -1.8520e+00],
         [ 2.3343e+00,  5.4164e-02, -1.9298e-01],
         [-1.2586e-01, -3.4317e-01, -4.5241e-01],
         [ 5.4491e-01, -5.4052e-02,  4.3319e-01],
         [-3.8786e-02, -1.3723e-02, -4.9978e-02],
         [-9.6825e-09, -1.3796e-08, -2.1168e-08]],

        [[ 3.5645e+00,  3.3643e+00, -4.4990e-01],
         [ 2.9834e+00,  2.9842e+00, -1.8043e+00],
         [ 5.2966e-02,  1.9467e-01,  2.7531e-01],
         [ 4.4492e-01,  4.1067e-01, -2.0944e+00],
         [-5.8094e-01, -8.2943e-02,  8.5317e-01],
         [ 1.1453e-01,  3.2998e-01,  4.0718e-01],
         [ 2.5169e+00, -3.7530e+00, -1.1332e+00],
         [-8.0073e-01, -2.2445e-01, -9.0770e-01],
         [-1.7629e-07, -3.9755e-08, -1.9151e-07]]])

# Premises

In [2]:
x = torch.rand(10, 2)
y = torch.rand(10)

In [3]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [4]:
model = ANFIS(
    input_size = 2,
    fuzzy_rules = 3,
    outputs = 1
)
model.init_premises(x)
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.187499     8.0  0.050267  0.189357     8.0  0.106526
Fuzzy rule 2  0.187499     8.0  0.425265  0.189357     8.0  0.485240
Fuzzy rule 3  0.187499     8.0  0.800264  0.189357     8.0  0.863954


In [6]:
def apply_params(optimizer, params):
    if params != {}:
        for param_group in optimizer.param_groups:
            for key, new_value in params.items():
                if key in param_group:
                    param_group[key] = new_value

In [7]:
loss_function = nn.functional.mse_loss

In [8]:
optimizer = torch.optim.Adam
params = {'lr': 0.1}

In [9]:
optimizer = optimizer([model._fuzzification_layer._premises])
apply_params(optimizer, params)
        
for batch_x, batch_y in loader:
    batch_y_copy = batch_y.clone().detach()
    if loader.dataset.tensors[0].dtype != loader.dataset.tensors[1].dtype:
        batch_y_copy = batch_y_copy.to(batch_x.dtype)
            
    optimizer.zero_grad()
    pred = model(batch_x)
    loss = loss_function(pred, batch_y_copy)
    loss.backward()
    optimizer.step()
    
    

In [10]:
model.show_premises_structure()

                a (x0)    b (x0)    c (x0)    a (x1)    b (x1)    c (x1)
Fuzzy rule 1  0.107377  8.221869 -0.027674 -0.137141  8.223636 -0.175811
Fuzzy rule 2 -0.109613  8.297024  0.722347  0.073248  8.247052  0.602319
Fuzzy rule 3  0.240726  8.024118  0.776368 -0.036441  8.214517  1.082119
