In [1]:
import sys
import os
import torch
import torch.utils.data as data
import torch.nn as nn

sys.path.append(os.path.abspath('../'))

from neuro_fuzzy_toolbox import ANFIS

# Gradient testing

## Rule reduced ANFIS

### Regression

#### Single output

In [2]:
x = torch.rand(10, 2)
y = torch.rand(10)
y

tensor([0.4072, 0.1807, 0.6863, 0.6741, 0.1424, 0.1257, 0.9919, 0.2005, 0.6156,
        0.6328])

In [3]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=1, output_type='regression', rule_reduced=True)

In [4]:
model.get_premises().shape

torch.Size([2, 3, 3])

In [5]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.221498     8.0  0.078418  0.212419     8.0  0.112679
Fuzzy rule 2  0.221498     8.0  0.521414  0.212419     8.0  0.537517
Fuzzy rule 3  0.221498     8.0  0.964410  0.212419     8.0  0.962354


In [6]:
model.get_consequents().shape

torch.Size([1, 3, 3])

In [7]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.461304  0.977295  0.069382
rule 2 -0.145087  0.752761 -0.757637
rule 3  0.201978  0.011258 -0.606137




In [9]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [10]:
model.predict(x)

array([[-0.28190058],
       [-0.62963855],
       [-0.3753108 ],
       [-0.5613053 ],
       [-0.74739444],
       [-0.27326128],
       [-0.10730655],
       [-0.34934598],
       [ 0.11655356],
       [-0.3508628 ]], dtype=float32)

In [11]:
model(x)

tensor([[-0.2819],
        [-0.6296],
        [-0.3753],
        [-0.5613],
        [-0.7474],
        [-0.2733],
        [-0.1073],
        [-0.3493],
        [ 0.1166],
        [-0.3509]], grad_fn=<TBackward0>)

In [12]:
y

tensor([0.4072, 0.1807, 0.6863, 0.6741, 0.1424, 0.1257, 0.9919, 0.2005, 0.6156,
        0.6328])

In [13]:
print(model._fuzzification_layer._premises.grad)

None


In [14]:
print(model._consequent_layer._consequents.grad)

None


In [15]:
model.predict(x)

array([[-0.28190058],
       [-0.62963855],
       [-0.3753108 ],
       [-0.5613053 ],
       [-0.74739444],
       [-0.27326128],
       [-0.10730655],
       [-0.34934598],
       [ 0.11655356],
       [-0.3508628 ]], dtype=float32)

In [16]:
model(x)

tensor([[-0.2819],
        [-0.6296],
        [-0.3753],
        [-0.5613],
        [-0.7474],
        [-0.2733],
        [-0.1073],
        [-0.3493],
        [ 0.1166],
        [-0.3509]], grad_fn=<TBackward0>)

In [17]:
model(x).squeeze()

tensor([-0.2819, -0.6296, -0.3753, -0.5613, -0.7474, -0.2733, -0.1073, -0.3493,
         0.1166, -0.3509], grad_fn=<SqueezeBackward0>)

In [18]:
loss = nn.functional.mse_loss(model(x).squeeze(), y)
loss

tensor(0.7463, grad_fn=<MseLossBackward0>)

In [19]:
loss.backward()

In [20]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-2.1662e-01,  5.5055e-03, -8.6534e-02],
         [ 1.3617e+00, -1.8698e-02, -8.2694e-01],
         [ 1.6857e+00, -6.4626e-02, -4.2218e-01]],

        [[-3.1691e+00,  9.4616e-02, -1.1144e+00],
         [ 6.1954e-01, -1.1421e-02,  8.1959e-02],
         [-9.6409e-03,  2.6899e-04,  3.3710e-03]]])


In [21]:
print(model._consequent_layer._consequents.grad)

tensor([[[-0.0087, -0.0408, -0.0547],
         [-0.6649, -0.8247, -1.5544],
         [-0.0033, -0.0326, -0.0343]]])


#### Multiple outputs

In [22]:
x = torch.rand(10, 3)
y = torch.rand(10, 2)
y

tensor([[0.2869, 0.0247],
        [0.9179, 0.2379],
        [0.6443, 0.7024],
        [0.1787, 0.6034],
        [0.3679, 0.1277],
        [0.0653, 0.3552],
        [0.0770, 0.4388],
        [0.8847, 0.4937],
        [0.9245, 0.9471],
        [0.0435, 0.0461]])

In [23]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=2, output_type='regression', rule_reduced=True)

In [24]:
model.get_premises().shape

torch.Size([3, 3, 3])

In [25]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)  \
Fuzzy rule 1  0.198646     8.0  0.065302  0.226961     8.0  0.008280   
Fuzzy rule 2  0.198646     8.0  0.462594  0.226961     8.0  0.462201   
Fuzzy rule 3  0.198646     8.0  0.859886  0.226961     8.0  0.916123   

                a (x2)  b (x2)    c (x2)  
Fuzzy rule 1  0.215252     8.0  0.128624  
Fuzzy rule 2  0.215252     8.0  0.559127  
Fuzzy rule 3  0.215252     8.0  0.989630  


In [26]:
model.get_consequents().shape

torch.Size([2, 3, 4])

In [27]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)   c2 (x2)        c3
rule 1  0.177888  0.853737  0.222389  0.197421
rule 2 -0.898722 -0.358963  0.920208 -0.959580
rule 3 -0.896605 -0.878845 -0.416707  0.307971


- Output 2:
         c0 (x0)   c1 (x1)   c2 (x2)        c3
rule 1  0.762448  0.956481 -0.871781  0.966296
rule 2  0.539027 -0.325953  0.407922  0.130752
rule 3 -0.206562 -0.608717  0.152595  0.855884




In [28]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [29]:
model.predict(x)

array([[-1.4209917 ,  0.700636  ],
       [-1.022884  ,  0.3111216 ],
       [-1.5199354 ,  0.29321206],
       [ 0.47833455,  0.8370391 ],
       [-1.5560433 ,  0.11631757],
       [-1.0019027 ,  0.32124925],
       [-0.4556676 ,  0.773929  ],
       [-0.64241344,  0.57620287],
       [-1.237752  ,  0.48775744],
       [ 0.97737837,  1.7090837 ]], dtype=float32)

In [30]:
model(x)

tensor([[-1.4210,  0.7006],
        [-1.0229,  0.3111],
        [-1.5199,  0.2932],
        [ 0.4783,  0.8370],
        [-1.5560,  0.1163],
        [-1.0019,  0.3212],
        [-0.4557,  0.7739],
        [-0.6424,  0.5762],
        [-1.2378,  0.4878],
        [ 0.9774,  1.7091]], grad_fn=<TBackward0>)

In [31]:
y

tensor([[0.2869, 0.0247],
        [0.9179, 0.2379],
        [0.6443, 0.7024],
        [0.1787, 0.6034],
        [0.3679, 0.1277],
        [0.0653, 0.3552],
        [0.0770, 0.4388],
        [0.8847, 0.4937],
        [0.9245, 0.9471],
        [0.0435, 0.0461]])

In [32]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [33]:
model(x)

tensor([[-1.4210,  0.7006],
        [-1.0229,  0.3111],
        [-1.5199,  0.2932],
        [ 0.4783,  0.8370],
        [-1.5560,  0.1163],
        [-1.0019,  0.3212],
        [-0.4557,  0.7739],
        [-0.6424,  0.5762],
        [-1.2378,  0.4878],
        [ 0.9774,  1.7091]], grad_fn=<TBackward0>)

In [34]:
loss = nn.functional.mse_loss(model(x), y)
loss

tensor(1.4121, grad_fn=<MseLossBackward0>)

In [35]:
loss.backward()

In [36]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-1.0295e+00, -8.9976e-04, -1.0670e+00],
         [ 1.6919e+00,  6.9159e-04, -1.7784e+00],
         [-3.5462e-05,  6.8703e-07,  1.6249e-05]],

        [[-2.5132e+00,  5.7732e-02, -1.1151e+00],
         [-5.3465e-02,  1.2036e-04,  4.7579e-02],
         [ 6.5381e-02, -9.4851e-04, -3.9208e-02]],

        [[ 6.9921e-02, -8.0804e-04,  4.5423e-02],
         [ 2.6050e+00, -4.5531e-02, -1.4601e+00],
         [ 8.6889e-03,  2.9761e-05, -9.8372e-03]]])


In [37]:
print(model._consequent_layer._consequents.grad)

tensor([[[ 0.0037,  0.0758,  0.0243,  0.1016],
         [-0.3885, -0.3648, -0.3345, -0.8555],
         [-0.3447, -0.3002, -0.3507, -0.4253]],

        [[ 0.0134,  0.1486,  0.0356,  0.1900],
         [ 0.0748,  0.0132,  0.0649,  0.1103],
         [-0.0692, -0.0594, -0.0702, -0.0853]]])


### Binary classification

#### Single ouput

In [38]:
x = torch.rand(10, 2)
y = torch.randint(0, 2, (10,))
y

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [39]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=1, output_type='binary', rule_reduced=True)
model.get_premises().shape

torch.Size([2, 3, 3])

In [40]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.172452     8.0  0.135044  0.201901     8.0  0.099089
Fuzzy rule 2  0.172452     8.0  0.479948  0.201901     8.0  0.502891
Fuzzy rule 3  0.172452     8.0  0.824851  0.201901     8.0  0.906692


In [41]:
model.get_consequents().shape

torch.Size([1, 3, 3])

In [42]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.619508  0.538391 -0.821865
rule 2 -0.041825 -0.794084  0.440977
rule 3  0.103066 -0.501712 -0.754889




In [43]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [44]:
model.predict(x)

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0]])

In [45]:
model(x)

tensor([[0.2857],
        [0.2440],
        [0.3360],
        [0.5472],
        [0.5319],
        [0.4735],
        [0.5131],
        [0.5397],
        [0.4234],
        [0.2940]], grad_fn=<SigmoidBackward0>)

In [46]:
y

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [47]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [48]:
model(x)

tensor([[0.2857],
        [0.2440],
        [0.3360],
        [0.5472],
        [0.5319],
        [0.4735],
        [0.5131],
        [0.5397],
        [0.4234],
        [0.2940]], grad_fn=<SigmoidBackward0>)

In [49]:
loss = nn.functional.binary_cross_entropy(model(x).squeeze(), y.to(model(x).dtype))
loss

tensor(0.5485, grad_fn=<BinaryCrossEntropyBackward0>)

In [50]:
loss.backward()

In [51]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-2.1586e-03,  6.4120e-05, -5.7325e-04],
         [ 4.6140e-01, -5.2493e-03,  2.4614e-01],
         [-9.0716e-02,  1.4416e-03,  4.4903e-02]],

        [[-2.0698e-02,  2.1088e-04, -1.3831e-02],
         [ 1.2556e-01, -1.5713e-03, -5.7460e-04],
         [-3.7031e-01,  6.5148e-03,  1.8702e-01]]])


In [52]:
print(model._consequent_layer._consequents.grad)

tensor([[[0.0196, 0.0227, 0.0912],
         [0.1401, 0.0981, 0.1975],
         [0.0179, 0.0248, 0.0301]]])


#### Multiple Outputs

In [53]:
x = torch.rand(10, 2)
y = torch.randint(0, 2, (10, 2))
y

tensor([[0, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [1, 0],
        [1, 1],
        [0, 0],
        [0, 0]])

In [54]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=2, output_type='binary', rule_reduced=True)
model.get_premises().shape

torch.Size([2, 3, 3])

In [55]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)   a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.204994     8.0  0.007034  0.14011     8.0  0.318724
Fuzzy rule 2  0.204994     8.0  0.417022  0.14011     8.0  0.598944
Fuzzy rule 3  0.204994     8.0  0.827009  0.14011     8.0  0.879163


In [56]:
model.get_consequents().shape

torch.Size([2, 3, 3])

In [57]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.101969  0.281014 -0.420911
rule 2  0.818008  0.748945  0.352077
rule 3 -0.650215 -0.138927 -0.885775


- Output 2:
         c0 (x0)   c1 (x1)        c2
rule 1  0.108706 -0.557631 -0.193753
rule 2  0.426635 -0.314839  0.070002
rule 3 -0.687223 -0.089385 -0.825604




In [58]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [59]:
model.predict(x)

array([[0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1]])

In [60]:
model(x)

tensor([[0.4177, 0.4084],
        [0.7293, 0.5246],
        [0.6705, 0.4230],
        [0.7564, 0.5286],
        [0.7452, 0.5190],
        [0.6994, 0.4834],
        [0.7418, 0.5004],
        [0.4199, 0.4031],
        [0.7712, 0.5264],
        [0.7953, 0.5681]], grad_fn=<SigmoidBackward0>)

In [61]:
y

tensor([[0, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [1, 0],
        [1, 1],
        [0, 0],
        [0, 0]])

In [62]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [63]:
model(x)

tensor([[0.4177, 0.4084],
        [0.7293, 0.5246],
        [0.6705, 0.4230],
        [0.7564, 0.5286],
        [0.7452, 0.5190],
        [0.6994, 0.4834],
        [0.7418, 0.5004],
        [0.4199, 0.4031],
        [0.7712, 0.5264],
        [0.7953, 0.5681]], grad_fn=<SigmoidBackward0>)

In [64]:
loss = nn.functional.binary_cross_entropy(model(x), y.to(model(x).dtype))
loss

tensor(0.7099, grad_fn=<BinaryCrossEntropyBackward0>)

In [65]:
loss.backward()

In [66]:
print(model._fuzzification_layer._premises.grad)

tensor([[[ 1.7498e-03, -2.4280e-05,  9.7649e-04],
         [ 1.6105e-01, -1.8278e-03, -5.9180e-02],
         [ 2.6557e-01, -5.2112e-03, -1.2348e-01]],

        [[-1.6979e-01,  1.6712e-03, -9.6783e-02],
         [-3.4709e-01,  4.6921e-03, -2.3431e-01],
         [-6.6207e-02,  1.2906e-03,  2.1753e-02]]])


In [67]:
print(model._consequent_layer._consequents.grad)

tensor([[[-0.0013, -0.0034, -0.0071],
         [ 0.0321,  0.0219,  0.0482],
         [-0.0014, -0.0034, -0.0038]],

        [[-0.0014, -0.0041, -0.0087],
         [ 0.0434,  0.0623,  0.0978],
         [ 0.0020,  0.0045,  0.0051]]])


### Multiclass classification

#### Single output

In [68]:
x = torch.rand(10, 2)
y = torch.randint(0, 4, (10,))
y

tensor([0, 1, 1, 1, 2, 2, 0, 1, 3, 0])

In [69]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=4, output_type='multiclass', rule_reduced=True)
model.get_premises().shape

torch.Size([2, 3, 3])

In [70]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.232587     8.0  0.022893  0.246464     8.0  0.009693
Fuzzy rule 2  0.232587     8.0  0.488066  0.246464     8.0  0.502621
Fuzzy rule 3  0.232587     8.0  0.953239  0.246464     8.0  0.995549


In [71]:
model.get_consequents().shape

torch.Size([4, 3, 3])

In [72]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.965832 -0.323224  0.252511
rule 2  0.809947 -0.311321  0.211573
rule 3 -0.959677  0.948421  0.511523


- Output 2:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.125717 -0.509166 -0.065966
rule 2  0.840420  0.084174  0.654132
rule 3 -0.170399  0.637116 -0.599627


- Output 3:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.233188  0.052761 -0.287922
rule 2  0.037529 -0.275330 -0.473778
rule 3 -0.376779  0.630491  0.818237


- Output 4:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.832071 -0.453395  0.187713
rule 2  0.705981  0.721544 -0.524818
rule 3  0.620825 -0.679008  0.851720




In [73]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [74]:
model.predict(x)

array([[1],
       [3],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [75]:
model(x)

tensor([[0.2576, 0.4881, 0.0744, 0.1799],
        [0.2274, 0.2777, 0.1849, 0.3100],
        [0.2952, 0.4587, 0.1034, 0.1428],
        [0.3175, 0.2237, 0.2421, 0.2167],
        [0.2961, 0.2251, 0.2069, 0.2719],
        [0.2242, 0.4568, 0.1064, 0.2126],
        [0.2310, 0.4291, 0.0911, 0.2488],
        [0.2729, 0.4810, 0.0852, 0.1609],
        [0.2116, 0.4667, 0.0849, 0.2368],
        [0.2523, 0.4866, 0.0752, 0.1858]], grad_fn=<SoftmaxBackward0>)

In [76]:
y

tensor([0, 1, 1, 1, 2, 2, 0, 1, 3, 0])

In [77]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [78]:
model(x)

tensor([[0.2576, 0.4881, 0.0744, 0.1799],
        [0.2274, 0.2777, 0.1849, 0.3100],
        [0.2952, 0.4587, 0.1034, 0.1428],
        [0.3175, 0.2237, 0.2421, 0.2167],
        [0.2961, 0.2251, 0.2069, 0.2719],
        [0.2242, 0.4568, 0.1064, 0.2126],
        [0.2310, 0.4291, 0.0911, 0.2488],
        [0.2729, 0.4810, 0.0852, 0.1609],
        [0.2116, 0.4667, 0.0849, 0.2368],
        [0.2523, 0.4866, 0.0752, 0.1858]], grad_fn=<SoftmaxBackward0>)

In [79]:
loss = nn.functional.cross_entropy(model(x), y)
loss.backward()

In [80]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-0.0448,  0.0030,  0.0022],
         [-1.0156,  0.0205, -0.0539],
         [ 0.2413, -0.0128, -0.0189]],

        [[ 0.0835, -0.0036,  0.0206],
         [-0.9130,  0.0203,  0.1684],
         [ 0.6434, -0.0273, -0.1622]]])


In [81]:
print(model._consequent_layer._consequents.grad)

tensor([[[ 0.0030,  0.0043,  0.0117],
         [-0.0186, -0.0215, -0.0198],
         [ 0.0009,  0.0009,  0.0026]],

        [[-0.0061, -0.0047, -0.0089],
         [-0.0028,  0.0252,  0.0002],
         [-0.0058, -0.0049, -0.0113]],

        [[-0.0003, -0.0027, -0.0132],
         [ 0.0084, -0.0001,  0.0067],
         [ 0.0016,  0.0019,  0.0035]],

        [[ 0.0034,  0.0031,  0.0103],
         [ 0.0129, -0.0036,  0.0129],
         [ 0.0032,  0.0021,  0.0051]]])


#### Multiple outputs (Multi Label)
 --- Pending Development ---

## Regular ANFIS

### Regression

#### Single Output

In [82]:
x = torch.rand(10, 2)
y = torch.rand(10)
y

tensor([0.7240, 0.1869, 0.3305, 0.0806, 0.7245, 0.4651, 0.8260, 0.2759, 0.7537,
        0.6008])

In [83]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=1, output_type='regression')

In [84]:
model.get_premises().shape

torch.Size([2, 3, 3])

In [85]:
model.show_premises_structure()

               a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.19047     8.0  0.131673  0.120382     8.0  0.153733
Fuzzy rule 2  0.19047     8.0  0.512612  0.120382     8.0  0.394497
Fuzzy rule 3  0.19047     8.0  0.893551  0.120382     8.0  0.635262


In [86]:
model.get_consequents().shape

torch.Size([1, 9, 3])

In [87]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1  0.825339  0.603133 -0.694444
rule 2 -0.734119 -0.732572 -0.823638
rule 3 -0.719285  0.152700 -0.353037
rule 4  0.340978  0.574633 -0.478439
rule 5 -0.809598 -0.961895  0.609486
rule 6 -0.570289  0.756480 -0.293430
rule 7  0.100709 -0.212550 -0.965769
rule 8 -0.156384 -0.816765 -0.930233
rule 9  0.724330  0.885706  0.208126




In [88]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [89]:
model.predict(x)

array([[-1.3628371 ],
       [-0.31312954],
       [-0.9122366 ],
       [-0.1185317 ],
       [-1.1870909 ],
       [-0.24331667],
       [-1.4392731 ],
       [-1.4015404 ],
       [-0.10620712],
       [-0.18403567]], dtype=float32)

In [90]:
model(x)

tensor([[-1.3628],
        [-0.3131],
        [-0.9122],
        [-0.1185],
        [-1.1871],
        [-0.2433],
        [-1.4393],
        [-1.4015],
        [-0.1062],
        [-0.1840]], grad_fn=<TBackward0>)

In [91]:
y

tensor([0.7240, 0.1869, 0.3305, 0.0806, 0.7245, 0.4651, 0.8260, 0.2759, 0.7537,
        0.6008])

In [92]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [93]:
model(x).squeeze()

tensor([-1.3628, -0.3131, -0.9122, -0.1185, -1.1871, -0.2433, -1.4393, -1.4015,
        -0.1062, -0.1840], grad_fn=<SqueezeBackward0>)

In [94]:
loss = nn.functional.mse_loss(model(x).squeeze(), y)
loss

tensor(1.9646, grad_fn=<MseLossBackward0>)

In [95]:
loss.backward()

In [96]:
print(model._fuzzification_layer._premises.grad)

tensor([[[ 4.3602e-04, -6.6649e-06,  2.2991e-04],
         [-5.5933e-01,  1.3944e-03, -5.1211e-01],
         [ 9.7816e-01, -1.7840e-03, -9.0687e-01]],

        [[-7.1186e-03,  6.0862e-05, -4.0347e-03],
         [ 8.4169e-03, -2.1896e-05, -1.0612e-03],
         [-1.7102e+00,  7.8917e-03,  1.2593e+00]]])


In [97]:
print(model._consequent_layer._consequents.grad)

tensor([[[-6.5699e-06, -1.8070e-05, -4.9634e-05],
         [-5.0334e-02, -1.3928e-01, -3.8226e-01],
         [-1.3696e-06, -1.8697e-06, -3.3200e-06],
         [-1.4746e-01, -4.1145e-02, -2.3252e-01],
         [-1.0113e-01, -7.4675e-02, -1.8522e-01],
         [-8.8494e-02, -1.0927e-01, -1.7202e-01],
         [-2.3865e-01, -4.8029e-02, -2.7261e-01],
         [-1.0004e+00, -5.2043e-01, -1.1976e+00],
         [-3.9698e-03, -2.3308e-03, -4.9402e-03]]])


#### Multiple Outputs

In [98]:
x = torch.rand(10, 2)
y = torch.rand(10, 2)
y

tensor([[0.4268, 0.2650],
        [0.1285, 0.0570],
        [0.0178, 0.7305],
        [0.5046, 0.8170],
        [0.4659, 0.2869],
        [0.1455, 0.2703],
        [0.0480, 0.9764],
        [0.8239, 0.9933],
        [0.8059, 0.7504],
        [0.2784, 0.7969]])

In [99]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=2, output_type='regression')
model.get_premises().shape

torch.Size([2, 3, 3])

In [100]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.222299     8.0  0.015027  0.198261     8.0  0.120091
Fuzzy rule 2  0.222299     8.0  0.459626  0.198261     8.0  0.516612
Fuzzy rule 3  0.222299     8.0  0.904224  0.198261     8.0  0.913133


In [101]:
model.get_consequents().shape

torch.Size([2, 9, 3])

In [102]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1  0.254559 -0.924360 -0.893968
rule 2  0.906214  0.500875  0.414608
rule 3 -0.452432  0.732237  0.498120
rule 4 -0.037744  0.401003 -0.670074
rule 5 -0.148006 -0.227990 -0.580735
rule 6 -0.104840  0.588139  0.987605
rule 7 -0.039736  0.491749  0.075482
rule 8 -0.096808 -0.582104 -0.285093
rule 9 -0.691778  0.329434 -0.049820


- Output 2:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.002235 -0.689800 -0.757484
rule 2  0.079625 -0.896054 -0.419587
rule 3  0.134552 -0.906203  0.305547
rule 4 -0.582177  0.311129 -0.758878
rule 5 -0.764779  0.176218 -0.061171
rule 6  0.771186 -0.698199 -0.574911
rule 7  0.717391  0.622613 -0.450999
rule 8  0.450410  0.317313  0.420233
rule 9  0.971535 -0.605335 -0.920153




In [103]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [104]:
model(x)

tensor([[-0.9926, -0.8779],
        [-0.7477, -0.3278],
        [ 1.0250, -0.4196],
        [-0.7416,  0.9474],
        [-0.6969,  1.0041],
        [-0.3436, -0.6376],
        [-0.9909, -0.8404],
        [ 0.1288,  0.2023],
        [-0.4216,  0.7363],
        [ 0.0556,  0.1240]], grad_fn=<TBackward0>)

In [105]:
y

tensor([[0.4268, 0.2650],
        [0.1285, 0.0570],
        [0.0178, 0.7305],
        [0.5046, 0.8170],
        [0.4659, 0.2869],
        [0.1455, 0.2703],
        [0.0480, 0.9764],
        [0.8239, 0.9933],
        [0.8059, 0.7504],
        [0.2784, 0.7969]])

In [106]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [107]:
loss = nn.functional.mse_loss(model(x), y)
loss

tensor(0.9286, grad_fn=<MseLossBackward0>)

In [108]:
loss.backward()

In [109]:
print(model._fuzzification_layer._premises.grad)

tensor([[[ 3.8879e-03,  3.1312e-05,  5.1021e-03],
         [ 6.1069e-01, -2.3181e-03,  8.3636e-01],
         [-6.9882e-02, -2.8062e-04,  8.0770e-02]],

        [[-8.8846e-01,  2.0909e-03, -8.0775e-01],
         [ 3.2999e-01, -9.8347e-05,  1.4087e-01],
         [-1.8262e-01,  8.2024e-04,  1.5326e-01]]])


In [110]:
print(model._consequent_layer._consequents.grad)

tensor([[[-3.1547e-02, -3.6674e-02, -2.3971e-01],
         [ 9.3933e-05,  4.9784e-03,  6.6142e-03],
         [ 1.4137e-03,  7.0578e-02,  9.4080e-02],
         [-3.4666e-03, -1.9778e-03, -9.2985e-03],
         [-4.0876e-02, -3.9305e-02, -8.9550e-02],
         [-5.1131e-06, -3.9729e-06, -4.6706e-06],
         [-8.2175e-02, -2.4955e-02, -1.0919e-01],
         [-2.7830e-01, -1.7903e-01, -3.3675e-01],
         [-4.5620e-02, -4.7576e-02, -5.3266e-02]],

        [[-3.0807e-02, -4.1302e-02, -2.9104e-01],
         [-1.1852e-04, -5.6953e-03, -7.6106e-03],
         [-1.6142e-03, -8.0587e-02, -1.0742e-01],
         [-6.4136e-03, -3.0010e-03, -1.2581e-02],
         [-1.7683e-02, -1.7114e-02, -3.8992e-02],
         [-6.2934e-06, -7.9280e-06, -8.9375e-06],
         [-9.9975e-02, -2.9964e-02, -1.3449e-01],
         [ 7.1462e-02,  4.6855e-02,  7.9170e-02],
         [-7.7675e-02, -8.2589e-02, -9.0322e-02]]])


### Binary classification

#### Single Output

In [111]:
x = torch.rand(10, 2)
y = torch.randint(0, 2, (10,))
y

tensor([1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [112]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=1, output_type='binary')
model.get_premises().shape

torch.Size([2, 3, 3])

In [113]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.226061     8.0  0.024104  0.232639     8.0  0.041374
Fuzzy rule 2  0.226061     8.0  0.476227  0.232639     8.0  0.506652
Fuzzy rule 3  0.226061     8.0  0.928350  0.232639     8.0  0.971930


In [114]:
model.get_consequents().shape

torch.Size([1, 9, 3])

In [115]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.096081  0.462363 -0.225886
rule 2  0.584555  0.260411  0.176128
rule 3 -0.721300 -0.194133  0.969655
rule 4  0.292512  0.399038  0.922134
rule 5  0.377410  0.961239  0.723520
rule 6 -0.066735  0.475428 -0.905254
rule 7 -0.196472 -0.620362 -0.093238
rule 8  0.382602  0.513871 -0.222858
rule 9  0.391978 -0.720030  0.237017




In [116]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [117]:
model.predict(x)

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [118]:
model(x)

tensor([[0.4259],
        [0.4753],
        [0.4187],
        [0.4299],
        [0.7127],
        [0.4604],
        [0.7763],
        [0.7165],
        [0.6068],
        [0.8120]], grad_fn=<SigmoidBackward0>)

In [119]:
y

tensor([1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [120]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [121]:
loss = nn.functional.binary_cross_entropy(model(x).squeeze(), y.to(model(x).dtype))
loss

tensor(0.8006, grad_fn=<BinaryCrossEntropyBackward0>)

In [122]:
loss.backward()

In [123]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-4.5433e-01,  4.6721e-04, -4.3781e-01],
         [ 1.0977e-02,  9.3109e-04, -4.2349e-01],
         [ 3.7176e-01, -9.5002e-04, -3.3967e-01]],

        [[-1.7029e-02,  1.1594e-04, -1.3474e-02],
         [-7.8258e-01,  2.9370e-03, -6.8735e-01],
         [ 8.1590e-02,  3.4726e-04, -9.3928e-02]]])


In [124]:
print(model._consequent_layer._consequents.grad)

tensor([[[ 1.2341e-03,  7.0136e-03,  4.6466e-02],
         [ 1.2738e-02,  4.6003e-02,  7.8414e-02],
         [ 1.2703e-04,  6.4700e-04,  9.6408e-04],
         [-1.6657e-02, -3.4526e-03, -2.3621e-02],
         [ 3.5446e-02,  5.1487e-02,  1.0369e-01],
         [-2.9128e-02, -3.9825e-02, -5.1616e-02],
         [-1.0326e-02, -7.3388e-03, -1.8278e-02],
         [-4.7651e-05, -1.0935e-05, -6.4311e-05],
         [ 4.4109e-02,  4.6175e-02,  4.7503e-02]]])


#### Multiple Outputs

In [125]:
x = torch.rand(10, 2)
y = torch.randint(0, 2, (10, 2))
y

tensor([[1, 0],
        [0, 0],
        [0, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [1, 1],
        [0, 1],
        [0, 0],
        [0, 1]])

In [126]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=2, output_type='binary')
model.get_premises().shape

torch.Size([2, 3, 3])

In [127]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.225227     8.0  0.050396  0.189086     8.0  0.186299
Fuzzy rule 2  0.225227     8.0  0.500850  0.189086     8.0  0.564471
Fuzzy rule 3  0.225227     8.0  0.951305  0.189086     8.0  0.942642


In [128]:
model.get_consequents().shape

torch.Size([2, 9, 3])

In [129]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.816087 -0.099772 -0.950925
rule 2 -0.510148  0.292300 -0.723555
rule 3 -0.894827  0.918854 -0.222527
rule 4 -0.397367  0.873089 -0.056102
rule 5 -0.003941 -0.334206  0.057884
rule 6 -0.335596 -0.320442  0.155990
rule 7  0.324260  0.745914 -0.105351
rule 8 -0.996368  0.536510  0.904891
rule 9 -0.455076 -0.729167  0.453573


- Output 2:
         c0 (x0)   c1 (x1)        c2
rule 1  0.830985  0.855782 -0.629303
rule 2 -0.462282 -0.500870 -0.201455
rule 3  0.789625  0.325511 -0.170550
rule 4  0.745201 -0.678577 -0.009276
rule 5 -0.378998 -0.781714 -0.974314
rule 6 -0.371045  0.131174  0.047240
rule 7 -0.060947 -0.373852 -0.655552
rule 8  0.981140 -0.987767  0.401127
rule 9  0.746889  0.827273  0.982083




In [130]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [131]:
model.predict(x)

array([[1, 1],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1]])

In [132]:
model(x)

tensor([[0.5028, 0.5300],
        [0.4192, 0.4865],
        [0.3428, 0.9209],
        [0.4977, 0.5406],
        [0.5173, 0.5488],
        [0.4807, 0.5520],
        [0.4566, 0.1606],
        [0.5794, 0.5755],
        [0.4228, 0.4914],
        [0.6453, 0.5439]], grad_fn=<SigmoidBackward0>)

In [133]:
y

tensor([[1, 0],
        [0, 0],
        [0, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [1, 1],
        [0, 1],
        [0, 0],
        [0, 1]])

In [134]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [135]:
model(x)

tensor([[0.5028, 0.5300],
        [0.4192, 0.4865],
        [0.3428, 0.9209],
        [0.4977, 0.5406],
        [0.5173, 0.5488],
        [0.4807, 0.5520],
        [0.4566, 0.1606],
        [0.5794, 0.5755],
        [0.4228, 0.4914],
        [0.6453, 0.5439]], grad_fn=<SigmoidBackward0>)

In [136]:
loss = nn.functional.binary_cross_entropy(model(x), y.to(model(x).dtype))
loss

tensor(0.8369, grad_fn=<BinaryCrossEntropyBackward0>)

In [137]:
loss.backward()

In [138]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-2.4754e-01,  1.5966e-04, -2.4199e-01],
         [ 3.5714e-01, -5.1102e-04, -2.0745e-02],
         [-1.9009e-02, -1.0726e-04,  2.2823e-02]],

        [[ 2.2498e-01, -6.1565e-04,  2.0039e-01],
         [-3.4390e-02, -2.7068e-05,  3.2016e-02],
         [-4.5874e-02,  3.2586e-04,  3.3966e-02]]])


In [139]:
print(model._consequent_layer._consequents.grad)

tensor([[[-2.9871e-06, -2.0799e-06, -7.2565e-06],
         [-1.3591e-05, -3.3431e-05, -4.2081e-05],
         [-4.6437e-03,  1.1094e-02,  9.6503e-03],
         [ 1.0305e-03, -2.0150e-03, -3.2029e-04],
         [-8.7409e-03, -1.7287e-02, -2.3844e-02],
         [ 1.6176e-02,  1.4592e-02,  1.5289e-02],
         [ 2.5295e-03,  1.3358e-03,  3.3513e-03],
         [ 1.6613e-02,  8.7737e-03,  2.2011e-02],
         [ 1.6312e-02,  1.5794e-02,  1.7152e-02]],

        [[ 4.7539e-06,  2.8498e-06,  1.1131e-05],
         [-2.9851e-06,  3.0900e-06, -1.8492e-07],
         [ 3.7458e-04, -1.6743e-02, -1.6953e-02],
         [ 2.3626e-02,  1.2126e-02,  5.3719e-02],
         [-1.8853e-02, -2.9488e-02, -4.3863e-02],
         [ 2.6839e-02,  4.1856e-02,  4.7118e-02],
         [-1.8529e-03, -9.7850e-04, -2.4548e-03],
         [-1.2168e-02, -6.4250e-03, -1.6122e-02],
         [ 4.3807e-02,  4.2409e-02,  4.6054e-02]]])


### Multiclass classification

#### Single output

In [140]:
x = torch.rand(10, 2)
y = torch.randint(0, 4, (10,))
y

tensor([3, 1, 3, 2, 3, 0, 2, 0, 2, 2])

In [141]:
model = ANFIS(x, init_fuzzy_rules=3, outputs=4, output_type='multiclass')
model.get_premises().shape

torch.Size([2, 3, 3])

In [142]:
model.show_premises_structure()

                a (x0)  b (x0)    c (x0)    a (x1)  b (x1)    c (x1)
Fuzzy rule 1  0.241497     8.0  0.007852  0.238365     8.0  0.014191
Fuzzy rule 2  0.241497     8.0  0.490845  0.238365     8.0  0.490921
Fuzzy rule 3  0.241497     8.0  0.973838  0.238365     8.0  0.967650


In [143]:
model.get_consequents().shape

torch.Size([4, 9, 3])

In [144]:
model.show_consequents_structure()

- Output 1:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.725030 -0.037313  0.216277
rule 2  0.326729  0.458359 -0.468954
rule 3  0.164263  0.420317  0.125152
rule 4  0.547544  0.889528 -0.787309
rule 5 -0.528762 -0.469563 -0.586205
rule 6  0.633602  0.831596  0.190577
rule 7 -0.677396 -0.956634  0.656568
rule 8 -0.768370 -0.744576 -0.382468
rule 9  0.869498 -0.980642 -0.131321


- Output 2:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.079183  0.602649 -0.104063
rule 2 -0.160952  0.038231 -0.911943
rule 3 -0.717819  0.519681  0.161077
rule 4 -0.636944 -0.360927  0.980592
rule 5  0.531812 -0.148693 -0.698030
rule 6 -0.224585  0.655748 -0.214906
rule 7  0.553097  0.225587 -0.575513
rule 8  0.592357  0.708222  0.264492
rule 9  0.292041  0.140016 -0.934236


- Output 3:
         c0 (x0)   c1 (x1)        c2
rule 1 -0.374329  0.208679  0.030200
rule 2  0.709746  0.709790 -0.950424
rule 3 -0.873176  0.049207 -0.167219
rule 4  0.539544 -0.504223  0.647524
rule 5  0.746228  0.297178  0.51439

In [145]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [146]:
model.predict(x)

array([[3],
       [3],
       [3],
       [3],
       [2],
       [1],
       [0],
       [3],
       [3],
       [3]])

In [147]:
model(x)

tensor([[0.1787, 0.1406, 0.3023, 0.3784],
        [0.2499, 0.1273, 0.1793, 0.4435],
        [0.2481, 0.1932, 0.2137, 0.3450],
        [0.2553, 0.1369, 0.1759, 0.4319],
        [0.0750, 0.1293, 0.5682, 0.2275],
        [0.0678, 0.5346, 0.1537, 0.2439],
        [0.4135, 0.1482, 0.1603, 0.2779],
        [0.2369, 0.1696, 0.1462, 0.4473],
        [0.1932, 0.1324, 0.2933, 0.3811],
        [0.2595, 0.2549, 0.1549, 0.3307]], grad_fn=<SoftmaxBackward0>)

In [148]:
y

tensor([3, 1, 3, 2, 3, 0, 2, 0, 2, 2])

In [149]:
print(model._fuzzification_layer._premises.grad)
print(model._consequent_layer._consequents.grad)

None
None


In [150]:
loss = nn.functional.cross_entropy(model(x), y)
loss

tensor(1.4271, grad_fn=<NllLossBackward0>)

In [151]:
loss.backward()

In [152]:
print(model._fuzzification_layer._premises.grad)

tensor([[[-1.8008e-05,  3.9691e-07, -8.6765e-06],
         [ 1.2773e-03,  1.2528e-05,  1.3229e-03],
         [-4.4001e-02,  2.3270e-04,  3.6931e-02]],

        [[-9.5043e-02,  2.8872e-04, -8.5787e-02],
         [-1.3426e-01,  5.7343e-04, -1.4979e-01],
         [ 5.9632e-02,  3.3460e-05, -6.0799e-02]]])


In [153]:
print(model._consequent_layer._consequents.grad)

tensor([[[ 7.8691e-04,  1.2042e-04,  8.4506e-03],
         [-4.1079e-04, -3.0682e-03, -1.2812e-03],
         [-9.2947e-04, -7.5941e-03, -1.0363e-02],
         [ 3.0550e-06,  1.1298e-06,  7.1024e-06],
         [ 6.9954e-04,  5.6279e-04,  1.2958e-03],
         [ 4.9725e-03,  5.7013e-03,  7.2439e-03],
         [ 2.4961e-03,  1.3859e-04,  2.9348e-03],
         [-5.6479e-03, -1.6088e-03, -5.7952e-03],
         [ 1.0775e-02,  1.0842e-02,  1.1897e-02]],

        [[ 5.8840e-04,  8.9171e-05,  6.3188e-03],
         [-1.0798e-03, -3.1520e-03, -8.3364e-03],
         [ 1.7097e-04,  1.3969e-03,  1.9062e-03],
         [ 4.0779e-06,  1.9052e-06,  8.5206e-06],
         [ 1.0546e-03,  7.6337e-04,  2.0478e-03],
         [ 1.1474e-03,  1.3163e-03,  1.6724e-03],
         [ 4.2869e-03,  6.6676e-04,  4.7644e-03],
         [ 4.9662e-03,  1.4285e-03,  5.1009e-03],
         [ 7.5446e-03,  7.6175e-03,  8.2893e-03]],

        [[ 6.6090e-04,  9.9539e-05,  7.0939e-03],
         [ 1.7143e-04, -4.6811e-03, -1.2126e-0

#### Multiple Outputs (Multi Label)
 --- Pending Development ---