In [3]:
import torch
import torch.nn as nn

In [4]:
cross_entropy = nn.functional.cross_entropy

binary_cross_entropy = nn.functional.binary_cross_entropy
binary_cross_entropy_with_logits = nn.functional.binary_cross_entropy_with_logits

mse_loss = nn.functional.mse_loss

l1_loss = nn.functional.l1_loss
nll_loss = nn.functional.nll_loss
kl_div = nn.functional.kl_div
cosine_similarity = nn.functional.cosine_similarity
hinge_embedding_loss = nn.functional.hinge_embedding_loss
margin_ranking_loss = nn.functional.margin_ranking_loss
multi_margin_loss = nn.functional.multi_margin_loss
smooth_l1_loss = nn.functional.smooth_l1_loss
soft_margin_loss = nn.functional.soft_margin_loss
triplet_margin_loss = nn.functional.triplet_margin_loss
ctc_loss = nn.functional.ctc_loss
poisson_nll_loss = nn.functional.poisson_nll_loss

# Cross Entropy

In [41]:
input = torch.randn(3, 5, requires_grad=True, dtype=torch.float32)
target = torch.randint(5, (3,), dtype=torch.long)

In [42]:
torch.long == torch.int64

True

In [43]:
torch.double == torch.float64

True

In [44]:
torch.float == torch.float32

True

In [45]:
torch.half == torch.float16

True

In [46]:
input

tensor([[-0.1961, -0.5419, -0.7315, -1.6524,  1.3631],
        [ 0.4666,  0.1013, -1.5226,  0.4668,  0.8545],
        [ 2.6421, -0.8227, -0.6236,  1.0706,  1.3507]], requires_grad=True)

In [47]:
target

tensor([2, 4, 4])

In [48]:
input.dtype, target.dtype

(torch.float32, torch.int64)

In [49]:
cross_entropy(input, target)

tensor(1.7745, grad_fn=<NllLossBackward0>)

In [50]:
nnCrossEntropy = nn.CrossEntropyLoss()

input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.int32).random_(5)

In [51]:
input

tensor([[-1.5158, -0.6438, -0.3281,  0.2871,  0.9944],
        [-0.4919,  0.2565, -1.0352,  0.5305, -1.8090],
        [-0.2138, -1.0568, -0.9910, -0.0570, -0.5497]], requires_grad=True)

In [52]:
target

tensor([4, 1, 4], dtype=torch.int32)

In [53]:
input.dtype, target.dtype

(torch.float32, torch.int32)

In [54]:
nnCrossEntropy(input, target)

RuntimeError: expected scalar type Long but found Int

# Binary Cross Entropy

In [74]:
input = torch.randn(3, 2, requires_grad=True)
target = torch.rand(3, 2, requires_grad=False, dtype=torch.double)

input

tensor([[ 0.5669, -2.7415],
        [-0.6967, -0.6591],
        [ 0.9948, -0.6479]], requires_grad=True)

In [75]:
target

tensor([[0.2922, 0.8680],
        [0.5637, 0.2612],
        [0.3486, 0.7247]], dtype=torch.float64)

In [76]:
b_input = torch.sigmoid(input)
b_input

tensor([[0.6381, 0.0606],
        [0.3326, 0.3410],
        [0.7300, 0.3435]], grad_fn=<SigmoidBackward0>)

In [77]:
b_input.dtype, target.dtype

(torch.float32, torch.float64)

In [78]:
binary_cross_entropy(b_input, target)

RuntimeError: Found dtype Double but expected Float