In [1]:
import sys
import os
import torch
import torch.utils.data as data
import torch.nn as nn

sys.path.append(os.path.abspath('../'))

In [2]:
from neuro_fuzzy_toolbox_old import Type3ANFIS
from neuro_fuzzy_toolbox_old import hybrid_algorithm, EarlyStopping

In [3]:
x = torch.rand(10, 3)

y = torch.randint(0, 2, (10,))

model = Type3ANFIS(x, init_rules=9, output_type='binary')

In [4]:
y

tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 0])

In [5]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [6]:
model.classes_prediction(x)

tensor([[0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1]])

In [7]:
model(x)

tensor([[0.2688],
        [0.5513],
        [0.2883],
        [0.2110],
        [0.5624],
        [0.5463],
        [0.6283],
        [0.3167],
        [0.5226],
        [0.6244]], grad_fn=<TBackward0>)

In [8]:
optimizer = torch.optim.Adam
params = {'lr': 0.001}

In [9]:
algorithm = hybrid_algorithm(epochs=20, loss_function=nn.functional.binary_cross_entropy, optimizer=optimizer, optim_params=params)

In [10]:
model.premises

tensor([[[0.0378, 0.0590],
         [0.1558, 0.0590],
         [0.2739, 0.0590],
         [0.3919, 0.0590],
         [0.5099, 0.0590],
         [0.6280, 0.0590],
         [0.7460, 0.0590],
         [0.8641, 0.0590],
         [0.9821, 0.0590]],

        [[0.0103, 0.0601],
         [0.1304, 0.0601],
         [0.2506, 0.0601],
         [0.3708, 0.0601],
         [0.4910, 0.0601],
         [0.6112, 0.0601],
         [0.7314, 0.0601],
         [0.8516, 0.0601],
         [0.9718, 0.0601]],

        [[0.1844, 0.0489],
         [0.2822, 0.0489],
         [0.3799, 0.0489],
         [0.4777, 0.0489],
         [0.5754, 0.0489],
         [0.6732, 0.0489],
         [0.7710, 0.0489],
         [0.8687, 0.0489],
         [0.9665, 0.0489]]])

In [11]:
algorithm.premisesUpdate(model, loader)
model.premises

tensor([[[0.0374, 0.0587],
         [0.1521, 0.0587],
         [0.2728, 0.0554],
         [0.3948, 0.0623],
         [0.5101, 0.0582],
         [0.6301, 0.0621],
         [0.7433, 0.0562],
         [0.8675, 0.0612],
         [0.9821, 0.0590]],

        [[0.0124, 0.0623],
         [0.1337, 0.0612],
         [0.2521, 0.0566],
         [0.3678, 0.0631],
         [0.4911, 0.0633],
         [0.6078, 0.0603],
         [0.7331, 0.0588],
         [0.8504, 0.0612],
         [0.9718, 0.0601]],

        [[0.1866, 0.0511],
         [0.2837, 0.0495],
         [0.3774, 0.0467],
         [0.4752, 0.0527],
         [0.5719, 0.0516],
         [0.6731, 0.0491],
         [0.7744, 0.0469],
         [0.8653, 0.0512],
         [0.9665, 0.0489]]])

In [12]:
y

tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 0])

In [13]:
model.classes_prediction(x)

tensor([[0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1]])

In [14]:
model.consequent_layer.consequents

Parameter containing:
tensor([[[-0.4892, -0.5286,  0.5044, -0.2388],
         [ 0.4329,  0.7019, -0.7934, -0.9876],
         [ 0.7529, -0.2027, -0.9884, -0.9844],
         [ 0.0656,  0.5592,  0.8964, -0.5912],
         [ 0.2171,  0.2001, -0.3146,  0.7770],
         [ 0.3258,  0.1877,  0.1232, -0.3128],
         [-0.9990,  0.0333,  0.8306,  0.6729],
         [-0.8547, -0.8781, -0.2432,  0.9695],
         [ 0.0927,  0.9180, -0.6420, -0.5612]]], requires_grad=True)

In [ ]:
algorithm.consequentsUpdate(model,loader)

In [16]:
model.consequent_layer.consequents

Parameter containing:
tensor([[[ 7.1642e-08,  3.6776e-06,  3.1776e-06,  8.4200e-06],
         [-2.5412e-01,  7.6392e-01,  4.7154e-01,  1.2606e+00],
         [-7.3256e-01,  5.1283e-01,  2.1181e-02, -2.0660e-01],
         [-1.0615e-02,  8.9786e-05, -5.5634e-03, -1.9737e-02],
         [-3.4666e-11, -3.6956e-12, -2.1417e-11, -6.7151e-11],
         [-7.0788e-06, -4.0461e-06, -4.4150e-06, -7.3619e-06],
         [-2.0434e-07, -1.1678e-07, -1.2743e-07, -2.1251e-07],
         [-1.2924e-10, -7.3876e-11, -8.0612e-11, -1.3442e-10],
         [-5.5350e-22, -3.1633e-22, -3.4518e-22, -5.7571e-22]]],
       requires_grad=True)